version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:13-jdk-buster

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: chmod +x mvnw && ./mvnw clean install

    store_test_results:
      - path: test-results